# Generated by Django 3.1.4 on 2021-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StdMgtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstudent',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
